##
## ScuphUtils 2.0 Configuration
##

server:
  # This server's name
  name: SomeServer

  # This server's owner
  owner: SomePlayer

  # This server's website
  website: http://example.com


banning:

  # Ban appeal message. If your server doesn't support appeals, set to "none"
  appeal_url: http://some-appeal-url.com


admins: [ScuphGamingUK, Prozza]